# Generated by Django 4.2 on 2023-04-17 09:33

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_fileuploader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileuploader',
            name='file_1',
            field=models.FileField(upload_to='upload/', validators=[core.validators.ExcelFileValidator()]),
        ),
        migrations.AlterField(
            model_name='fileuploader',
            name='file_2',
            field=models.FileField(upload_to='upload/', validators=[core.validators.ExcelFileValidator()]),
        ),
    ]
