PR_VENDOR_GSTREG_NO="Vendor_GST_REG"
PR_VENDOR_NAME="Vendor_Name"
PR_INVOICE_NUMBER="Invoice_Number"
PR_INVOICE_DATE_TEXT="Invoice_Date_Text"
PR_TOTAL_TAX="Total_Tax"
PR_IGST="IGST"
PR_SGST="SGST"
PR_CGST="CGST"
PR_UTGST="UTGST"


R2_VENDOR_GSTREG_NO="GSTIN_of_Supplier"
R2_VENDOR_NAME="Legal_Name_Of Supplier"
R2_INVOICE_NUMBER="Inv_CN_DN_Number_Final"
R2_INVOICE_DATE_TEXT="Inv_CN_DN_Date_Text"
R2_TOTAL_TAX="Total_Tax"
R2_R1_FILING_STATUS="GSTR_1_5_Filing_Status"
R2_ATTRACT_RCM="Supply_Attract_Reverse_Charge"
R2_IGST="IGST"
R2_SGST="SGST"
R2_CGST="CGST"
R2_UTGST="UTGST"


EXPORT_SUMMARY_NAME="GSTR2 Vs PR Reconciliation_Summary.xlsx"
EXPORT_SUMMARY_SHEET="Summary"

GSTR2A_SHEET_NAME="Main_2A_Format"
ITR_SHEET_NAME="Main_ITR_Format"
CHECKLIST_SHEET_NAME="Important_Checklist"

